version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: reddy
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
    ports:
     - "5432:5432"
